-- Table: public.adjunto

-- DROP TABLE IF EXISTS public.adjunto;

CREATE TABLE IF NOT EXISTS public.adjunto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tramite_id bigint NOT NULL,
    tipo_documento_id bigint NOT NULL,
    nombre_archivo character varying COLLATE pg_catalog."default" NOT NULL,
    url character varying COLLATE pg_catalog."default" NOT NULL,
    subido_por bigint NOT NULL,
    creado_en date NOT NULL,
    CONSTRAINT adjunto_pkey PRIMARY KEY (id),
    CONSTRAINT adjunto_subido_por_fkey FOREIGN KEY (subido_por)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT adjunto_tipo_documento_id_fkey FOREIGN KEY (tipo_documento_id)
        REFERENCES public.tipo_documento (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT adjunto_tramite_id_fkey FOREIGN KEY (tramite_id)
        REFERENCES public.tramite (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.adjunto
    OWNER to demo;
-- Index: adjunto_tramite_id_index

-- DROP INDEX IF EXISTS public.adjunto_tramite_id_index;

CREATE INDEX IF NOT EXISTS adjunto_tramite_id_index
    ON public.adjunto USING btree
    (tramite_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;