-- Table: public.seguimiento

-- DROP TABLE IF EXISTS public.seguimiento;

CREATE TABLE IF NOT EXISTS public.seguimiento
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tramite_id bigint NOT NULL,
    creado_por bigint NOT NULL,
    tipo_evento character varying COLLATE pg_catalog."default" NOT NULL,
    comentario text COLLATE pg_catalog."default",
    ultimo_estado character varying COLLATE pg_catalog."default",
    nuevo_estado character varying COLLATE pg_catalog."default",
    creado_en date NOT NULL,
    CONSTRAINT seguimiento_pkey PRIMARY KEY (id),
    CONSTRAINT seguimiento_creado_por_fkey FOREIGN KEY (creado_por)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT seguimiento_tramite_id_fkey FOREIGN KEY (tramite_id)
        REFERENCES public.tramite (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT tipo_evento_nombre_chk CHECK (tipo_evento::text = ANY (ARRAY['COMENTARIO'::character varying, 'ASIGNACION'::character varying, 'CAMBIO_ESTADO'::character varying, 'CREACION'::character varying]::text[])),
    CONSTRAINT seguimiento_comentario_chk CHECK (tipo_evento::text <> 'COMENTARIO'::text OR comentario IS NOT NULL)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.seguimiento
    OWNER to demo;
-- Index: seguimiento_tramite_id_index

-- DROP INDEX IF EXISTS public.seguimiento_tramite_id_index;

CREATE INDEX IF NOT EXISTS seguimiento_tramite_id_index
    ON public.seguimiento USING btree
    (tramite_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;