-- Table: public.tipo_documento

-- DROP TABLE IF EXISTS public.tipo_documento;

CREATE TABLE IF NOT EXISTS public.tipo_documento
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    codigo character varying COLLATE pg_catalog."default" NOT NULL,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    es_activo boolean NOT NULL,
    creado_en date NOT NULL,
    actualizado_en date,
    CONSTRAINT tipo_documento_pkey PRIMARY KEY (id),
    CONSTRAINT tipo_documento_codigo_key UNIQUE (codigo)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tipo_documento
    OWNER to demo;