INSERT INTO public.tipo_tramite (codigo, nombre, descripcion, es_activo, creado_en) VALUES
('TT-001', 'Homologación', 'Solicitud para homologar asignaturas/creditos.', true, CURRENT_DATE),
('TT-002', 'Cancelación de semestre', 'Solicitud para cancelar el semestre en curso.', true, CURRENT_DATE),
('TT-003', 'Aplazamiento de semestre', 'Solicitud para aplazar el semestre (reserva temporal).', true, CURRENT_DATE),
('TT-004', 'Reintegro / Reingreso', 'Solicitud para retomar estudios tras retiro o pérdida de cupo.', true, CURRENT_DATE),
('TT-005', 'Reserva de cupo', 'Solicitud para reservar cupo por una vigencia definida.', true, CURRENT_DATE),
('TT-006', 'Adición de materias', 'Solicitud de adición de asignaturas fuera de fecha ordinaria.', true, CURRENT_DATE),
('TT-007', 'Cancelación de materias', 'Solicitud de cancelación de asignaturas.', true, CURRENT_DATE),
('TT-008', 'Cambio de programa', 'Solicitud de cambio de programa académico.', true, CURRENT_DATE),
('TT-009', 'Traslado interno', 'Solicitud de traslado entre programas dentro de la institución.', true, CURRENT_DATE),
('TT-010', 'Traslado externo', 'Solicitud de traslado desde/hacia otra institución.', true, CURRENT_DATE),
('TT-011', 'Certificado de estudios', 'Generación de certificado de estudios.', true, CURRENT_DATE),
('TT-012', 'Certificado de notas', 'Generación de certificado/histórico de calificaciones.', true, CURRENT_DATE),
('TT-013', 'Corrección de datos', 'Corrección de datos personales/registro académico.', true, CURRENT_DATE),
('TT-014', 'Solicitud de grado', 'Radicación para proceso de grado.', true, CURRENT_DATE),
('TT-015', 'Duplicado de diploma/acta', 'Solicitud de duplicado por pérdida o deterioro.', true, CURRENT_DATE),
('TT-016', 'Paz y salvo', 'Solicitud de paz y salvo académico/financiero.', true, CURRENT_DATE),
('TT-017', 'Validación de pago', 'Revisión/validación de pagos asociados al estudiante.', true, CURRENT_DATE),
('TT-018', 'Devolución de pago', 'Solicitud de devolución o ajuste de valores pagados.', true, CURRENT_DATE);
