-- Table: public.tramite

-- DROP TABLE IF EXISTS public.tramite;

CREATE TABLE IF NOT EXISTS public.tramite
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    radicado_por bigint NOT NULL,
    tipo_tramite_id bigint NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    estado character varying COLLATE pg_catalog."default" NOT NULL,
    asignado_a bigint,
    numero_radicado bigint,
    finalizado_en date,
    creado_en date NOT NULL,
    actualizado_en date NOT NULL,
    CONSTRAINT tramite_pkey PRIMARY KEY (id),
    CONSTRAINT tramite_numero_radicado_key UNIQUE (numero_radicado),
    CONSTRAINT tramite_asignado_a_fkey FOREIGN KEY (asignado_a)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT tramite_radicado_por_fkey FOREIGN KEY (radicado_por)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT tramite_tipo_tramite_id_fkey FOREIGN KEY (tipo_tramite_id)
        REFERENCES public.tipo_tramite (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT estado_nombre_chk CHECK (estado::text = ANY (ARRAY['RADICADO'::character varying, 'EN_PROCESO'::character varying, 'FINALIZADO'::character varying, 'RECHAZADO'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tramite
    OWNER to demo;
-- Index: tramite_asignado_a_index

-- DROP INDEX IF EXISTS public.tramite_asignado_a_index;

CREATE INDEX IF NOT EXISTS tramite_asignado_a_index
    ON public.tramite USING btree
    (asignado_a ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: tramite_radicado_por_index

-- DROP INDEX IF EXISTS public.tramite_radicado_por_index;

CREATE INDEX IF NOT EXISTS tramite_radicado_por_index
    ON public.tramite USING btree
    (radicado_por ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: tramite_tipo_tramite_id_index

-- DROP INDEX IF EXISTS public.tramite_tipo_tramite_id_index;

CREATE INDEX IF NOT EXISTS tramite_tipo_tramite_id_index
    ON public.tramite USING btree
    (tipo_tramite_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;