-- Table: public.usuario

-- DROP TABLE IF EXISTS public.usuario;

CREATE TABLE IF NOT EXISTS public.usuario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying COLLATE pg_catalog."default" NOT NULL,
    rol character varying COLLATE pg_catalog."default" NOT NULL,
    es_activo boolean NOT NULL,
    creado_en date,
    actualizado_en date,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT usuario_email_key UNIQUE (email),
    CONSTRAINT rol_nombre_chk CHECK (rol::text = ANY (ARRAY['ROLE_ESTUDIANTE'::character varying, 'ROLE_DOCENTE'::character varying, 'ROLE_ADMINISTRATIVO'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.usuario
    OWNER to demo;