-- Table: public.adjunto

-- DROP TABLE IF EXISTS public.adjunto;

CREATE TABLE IF NOT EXISTS public.adjunto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tramite_id bigint NOT NULL,
    tipo_documento_id bigint NOT NULL,
    nombre_archivo character varying COLLATE pg_catalog."default" NOT NULL,
    subido_por bigint NOT NULL,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    servicio_almacenamiento text COLLATE pg_catalog."default" NOT NULL DEFAULT 'LOCAL'::text,
    identificador_almacenamiento text COLLATE pg_catalog."default" NOT NULL,
    tipo_mime text COLLATE pg_catalog."default" NOT NULL,
    tamano_bytes bigint NOT NULL,
    sha256 text COLLATE pg_catalog."default" NOT NULL,
    estado_analisis_virus text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDIENTE'::text,
    analizado_en timestamp with time zone,
    esta_cuarentenado boolean NOT NULL DEFAULT false,
    CONSTRAINT adjunto_pkey PRIMARY KEY (id),
    CONSTRAINT adjunto_identificador_almacenamiento_key UNIQUE (identificador_almacenamiento),
    CONSTRAINT adjunto_subido_por_fkey FOREIGN KEY (subido_por)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT adjunto_tipo_documento_id_fkey FOREIGN KEY (tipo_documento_id)
        REFERENCES public.tipo_documento (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT adjunto_tramite_id_fkey FOREIGN KEY (tramite_id)
        REFERENCES public.tramite (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT adjunto_tamano_bytes_chk CHECK (tamano_bytes >= 0),
    CONSTRAINT adjunto_sha256_hex_chk CHECK (sha256 ~ '^[0-9a-f]{64}$'::text),
    CONSTRAINT adjunto_identificador_almacenamiento_safe_chk CHECK (identificador_almacenamiento IS NOT NULL AND length(identificador_almacenamiento) > 0 AND identificador_almacenamiento !~ '^/'::text AND identificador_almacenamiento !~~ '%..%'::text),
    CONSTRAINT adjunto_tipo_mime_chk CHECK (lower(tipo_mime) = ANY (ARRAY['application/pdf'::text, 'image/jpeg'::text, 'image/png'::text, 'application/msword'::text, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'::text])),
    CONSTRAINT adjunto_servicio_almacenamiento_chk CHECK (servicio_almacenamiento = 'LOCAL'::text),
    CONSTRAINT adjunto_estado_analisis_virus_chk CHECK (estado_analisis_virus = ANY (ARRAY['PENDIENTE'::text, 'SEGURO'::text, 'AMENAZA'::text]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.adjunto
    OWNER to demo;

-- Trigger: check_max_per_tipo_tramite_insert_update

-- DROP TRIGGER IF EXISTS check_max_per_tipo_tramite_insert_update ON public.adjunto;

CREATE OR REPLACE TRIGGER check_max_per_tipo_tramite_insert_update
    BEFORE INSERT OR UPDATE OF tramite_id, tipo_documento_id
    ON public.adjunto
    FOR EACH ROW
    EXECUTE FUNCTION public.check_adjunto_max_per_tipo_tramite();

-- Trigger: check_tipo_documento_vs_tramite_insert_update

-- DROP TRIGGER IF EXISTS check_tipo_documento_vs_tramite_insert_update ON public.adjunto;

CREATE OR REPLACE TRIGGER check_tipo_documento_vs_tramite_insert_update
    BEFORE INSERT OR UPDATE OF tramite_id, tipo_documento_id
    ON public.adjunto
    FOR EACH ROW
    EXECUTE FUNCTION public.check_adjunto_tipo_documento_vs_tramite();

-- Trigger: normalize_identificador_almacenamiento_insert_update

-- DROP TRIGGER IF EXISTS normalize_identificador_almacenamiento_insert_update ON public.adjunto;

CREATE OR REPLACE TRIGGER normalize_identificador_almacenamiento_insert_update
    BEFORE INSERT OR UPDATE OF identificador_almacenamiento
    ON public.adjunto
    FOR EACH ROW
    EXECUTE FUNCTION public.normalize_adjunto_identificador_almacenamiento();

-- Trigger: set_estado_analisis_virus_timestamp_insert_update

-- DROP TRIGGER IF EXISTS set_estado_analisis_virus_timestamp_insert_update ON public.adjunto;

CREATE OR REPLACE TRIGGER set_estado_analisis_virus_timestamp_insert_update
    BEFORE INSERT OR UPDATE OF estado_analisis_virus
    ON public.adjunto
    FOR EACH ROW
    EXECUTE FUNCTION public.set_adjunto_virus_scan_timestamp();