-- Table: public.adjunto

-- DROP TABLE IF EXISTS public.adjunto;

CREATE TABLE IF NOT EXISTS public.adjunto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tramite_id bigint NOT NULL,
    tipo_documento_id bigint NOT NULL,
    nombre_archivo character varying COLLATE pg_catalog."default" NOT NULL,
    subido_por bigint NOT NULL,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    storage_backend text COLLATE pg_catalog."default" NOT NULL DEFAULT 'FS'::text,
    storage_key text COLLATE pg_catalog."default" NOT NULL,
    mime_type text COLLATE pg_catalog."default" NOT NULL,
    tamano_bytes bigint NOT NULL,
    sha256 text COLLATE pg_catalog."default" NOT NULL,
    version integer NOT NULL DEFAULT 1,
    virus_scan_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::text,
    actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
    virus_scan_at timestamp with time zone,
    quarantine boolean NOT NULL DEFAULT false,
    CONSTRAINT adjunto_pkey PRIMARY KEY (id),
    CONSTRAINT adjunto_subido_por_fkey FOREIGN KEY (subido_por)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT adjunto_tipo_documento_id_fkey FOREIGN KEY (tipo_documento_id)
        REFERENCES public.tipo_documento (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT adjunto_tramite_id_fkey FOREIGN KEY (tramite_id)
        REFERENCES public.tramite (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT adjunto_tamano_bytes_check CHECK (tamano_bytes >= 0),
    CONSTRAINT adjunto_virus_scan_status_chk CHECK (virus_scan_status = ANY (ARRAY['PENDING'::text, 'CLEAN'::text, 'INFECTED'::text])),
    CONSTRAINT adjunto_storage_backend_chk CHECK (storage_backend = 'FS'::text),
    CONSTRAINT adjunto_sha256_hex_chk CHECK (sha256 ~ '^[0-9a-f]{64}$'::text),
    CONSTRAINT adjunto_version_chk CHECK (version >= 1),
    CONSTRAINT adjunto_storage_key_safe_chk CHECK (storage_key IS NOT NULL AND length(storage_key) > 0 AND storage_key !~ '^/'::text AND storage_key !~~ '%..%'::text),
    CONSTRAINT adjunto_mime_type_chk CHECK (mime_type ~ '^[A-Za-z0-9.+-]+/[A-Za-z0-9.+-]+$'::text)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.adjunto
    OWNER to demo;
-- Index: ix_adj_scan_pending

-- DROP INDEX IF EXISTS public.ix_adj_scan_pending;

CREATE INDEX IF NOT EXISTS ix_adj_scan_pending
    ON public.adjunto USING btree
    (virus_scan_status COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default
    WHERE virus_scan_status = 'PENDING'::text;
-- Index: ix_adj_subido_por

-- DROP INDEX IF EXISTS public.ix_adj_subido_por;

CREATE INDEX IF NOT EXISTS ix_adj_subido_por
    ON public.adjunto USING btree
    (subido_por ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: ix_adj_tram_tipodoc

-- DROP INDEX IF EXISTS public.ix_adj_tram_tipodoc;

CREATE INDEX IF NOT EXISTS ix_adj_tram_tipodoc
    ON public.adjunto USING btree
    (tramite_id ASC NULLS LAST, tipo_documento_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: ix_adj_tramite_fecha

-- DROP INDEX IF EXISTS public.ix_adj_tramite_fecha;

CREATE INDEX IF NOT EXISTS ix_adj_tramite_fecha
    ON public.adjunto USING btree
    (tramite_id ASC NULLS LAST, creado_en DESC NULLS FIRST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: ix_adjunto_sha256

-- DROP INDEX IF EXISTS public.ix_adjunto_sha256;

CREATE INDEX IF NOT EXISTS ix_adjunto_sha256
    ON public.adjunto USING btree
    (sha256 COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: ux_adj_tram_arch_ver

-- DROP INDEX IF EXISTS public.ux_adj_tram_arch_ver;

CREATE UNIQUE INDEX IF NOT EXISTS ux_adj_tram_arch_ver
    ON public.adjunto USING btree
    (tramite_id ASC NULLS LAST, nombre_archivo COLLATE pg_catalog."default" ASC NULLS LAST, version ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: ux_adjunto_path

-- DROP INDEX IF EXISTS public.ux_adjunto_path;

CREATE UNIQUE INDEX IF NOT EXISTS ux_adjunto_path
    ON public.adjunto USING btree
    (storage_key COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

-- Trigger: set_updated_at_adjunto

-- DROP TRIGGER IF EXISTS set_updated_at_adjunto ON public.adjunto;

CREATE OR REPLACE TRIGGER set_updated_at_adjunto
    BEFORE UPDATE 
    ON public.adjunto
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();

-- Trigger: trg_enforce_max_adjuntos

-- DROP TRIGGER IF EXISTS trg_enforce_max_adjuntos ON public.adjunto;

CREATE OR REPLACE TRIGGER trg_enforce_max_adjuntos
    BEFORE INSERT OR UPDATE OF tramite_id, tipo_documento_id
    ON public.adjunto
    FOR EACH ROW
    EXECUTE FUNCTION public.enforce_max_adjuntos();

-- Trigger: trg_norm_storage_key

-- DROP TRIGGER IF EXISTS trg_norm_storage_key ON public.adjunto;

CREATE OR REPLACE TRIGGER trg_norm_storage_key
    BEFORE INSERT OR UPDATE OF storage_key
    ON public.adjunto
    FOR EACH ROW
    EXECUTE FUNCTION public.normalize_storage_key();

-- Trigger: trg_set_virus_scan_at

-- DROP TRIGGER IF EXISTS trg_set_virus_scan_at ON public.adjunto;

CREATE OR REPLACE TRIGGER trg_set_virus_scan_at
    BEFORE INSERT OR UPDATE OF virus_scan_status
    ON public.adjunto
    FOR EACH ROW
    EXECUTE FUNCTION public.set_virus_scan_at();

-- Trigger: trg_validar_adjuntos_tipo_tramite

-- DROP TRIGGER IF EXISTS trg_validar_adjuntos_tipo_tramite ON public.adjunto;

CREATE OR REPLACE TRIGGER trg_validar_adjuntos_tipo_tramite
    BEFORE INSERT OR UPDATE OF tramite_id, tipo_documento_id
    ON public.adjunto
    FOR EACH ROW
    EXECUTE FUNCTION public.validar_adjuntos_tipo_tramite();