-- Role: demo
-- DROP ROLE IF EXISTS demo;

CREATE ROLE demo WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  BYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:goaT7j37uiXL5CXSN04Y9Q==$rQGwLbQbVQ7qu8t7+Qb4czCdnHN5aDUH6sZmJQwyNgE=:hgRGLtdgobsv+PDVW8dypWd9vz+U6edI9rsbBFegsTk=';