-- Table: public.seguimiento

-- DROP TABLE IF EXISTS public.seguimiento;

CREATE TABLE IF NOT EXISTS public.seguimiento
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tramite_id bigint NOT NULL,
    creado_por bigint NOT NULL,
    tipo_evento character varying COLLATE pg_catalog."default" NOT NULL,
    ultimo_estado character varying COLLATE pg_catalog."default",
    nuevo_estado character varying COLLATE pg_catalog."default",
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    comentario text COLLATE pg_catalog."default",
    asignado_a bigint,
    comentario_tsv tsvector GENERATED ALWAYS AS (to_tsvector('spanish'::regconfig, COALESCE(comentario, ''::text))) STORED,
    CONSTRAINT seguimiento_pkey PRIMARY KEY (id),
    CONSTRAINT seguimiento_asignado_a_fkey FOREIGN KEY (asignado_a)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT seguimiento_creado_por_fkey FOREIGN KEY (creado_por)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT seguimiento_tramite_id_fkey FOREIGN KEY (tramite_id)
        REFERENCES public.tramite (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.seguimiento
    OWNER to demo;
-- Index: seguimiento_asignado_a_creado_en_index

-- DROP INDEX IF EXISTS public.seguimiento_asignado_a_creado_en_index;

CREATE INDEX IF NOT EXISTS seguimiento_asignado_a_creado_en_index
    ON public.seguimiento USING btree
    (asignado_a ASC NULLS LAST, creado_en DESC NULLS FIRST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: seguimiento_creado_por_index

-- DROP INDEX IF EXISTS public.seguimiento_creado_por_index;

CREATE INDEX IF NOT EXISTS seguimiento_creado_por_index
    ON public.seguimiento USING btree
    (creado_por ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: seguimiento_tramite_id_creado_en_asignacion_index

-- DROP INDEX IF EXISTS public.seguimiento_tramite_id_creado_en_asignacion_index;

CREATE INDEX IF NOT EXISTS seguimiento_tramite_id_creado_en_asignacion_index
    ON public.seguimiento USING btree
    (tramite_id ASC NULLS LAST, creado_en DESC NULLS FIRST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default
    WHERE tipo_evento::text = 'ASIGNACION'::text;
-- Index: seguimiento_tramite_id_creado_en_cambio_estado_index

-- DROP INDEX IF EXISTS public.seguimiento_tramite_id_creado_en_cambio_estado_index;

CREATE INDEX IF NOT EXISTS seguimiento_tramite_id_creado_en_cambio_estado_index
    ON public.seguimiento USING btree
    (tramite_id ASC NULLS LAST, creado_en DESC NULLS FIRST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default
    WHERE tipo_evento::text = 'CAMBIO_ESTADO'::text;
-- Index: seguimiento_tramite_id_id_index

-- DROP INDEX IF EXISTS public.seguimiento_tramite_id_id_index;

CREATE INDEX IF NOT EXISTS seguimiento_tramite_id_id_index
    ON public.seguimiento USING btree
    (tramite_id ASC NULLS LAST, id DESC NULLS FIRST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;