-- Table: public.tipo_documento

-- DROP TABLE IF EXISTS public.tipo_documento;

CREATE TABLE IF NOT EXISTS public.tipo_documento
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    codigo character varying COLLATE pg_catalog."default" NOT NULL,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    es_activo boolean NOT NULL DEFAULT true,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT tipo_documento_pkey PRIMARY KEY (id),
    CONSTRAINT tipo_documento_codigo_key UNIQUE (codigo),
    CONSTRAINT tipo_documento_nombre_not_blank_chk CHECK (btrim(COALESCE(nombre, ''::character varying)::text) <> ''::text),
    CONSTRAINT tipo_documento_codigo_format_chk CHECK (codigo::text ~ '^[a-z0-9_.]+$'::text)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tipo_documento
    OWNER to demo;
-- Index: ix_tipo_documento_activo

-- DROP INDEX IF EXISTS public.ix_tipo_documento_activo;

CREATE INDEX IF NOT EXISTS ix_tipo_documento_activo
    ON public.tipo_documento USING btree
    (es_activo ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: ux_tipo_documento_nombre_canon

-- DROP INDEX IF EXISTS public.ux_tipo_documento_nombre_canon;

CREATE UNIQUE INDEX IF NOT EXISTS ux_tipo_documento_nombre_canon
    ON public.tipo_documento USING btree
    (lower(btrim(nombre::text)) COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

-- Trigger: set_updated_at_tipo_documento

-- DROP TRIGGER IF EXISTS set_updated_at_tipo_documento ON public.tipo_documento;

CREATE OR REPLACE TRIGGER set_updated_at_tipo_documento
    BEFORE UPDATE 
    ON public.tipo_documento
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();

-- Trigger: trg_norm_tipo_documento_codigo

-- DROP TRIGGER IF EXISTS trg_norm_tipo_documento_codigo ON public.tipo_documento;

CREATE OR REPLACE TRIGGER trg_norm_tipo_documento_codigo
    BEFORE INSERT OR UPDATE OF codigo
    ON public.tipo_documento
    FOR EACH ROW
    EXECUTE FUNCTION public.normalize_tipo_documento_codigo();