-- Table: public.tipo_tramite

-- DROP TABLE IF EXISTS public.tipo_tramite;

CREATE TABLE IF NOT EXISTS public.tipo_tramite
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    codigo character varying COLLATE pg_catalog."default" NOT NULL,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying COLLATE pg_catalog."default",
    es_activo boolean NOT NULL DEFAULT true,
    CONSTRAINT tipo_tramite_pkey PRIMARY KEY (id),
    CONSTRAINT tipo_tramite_codigo_key UNIQUE (codigo),
    CONSTRAINT tipo_tramite_codigo_format_chk CHECK (codigo::text ~ '^[a-z0-9_.]+$'::text),
    CONSTRAINT tipo_tramite_nombre_not_blank_chk CHECK (btrim(COALESCE(nombre, ''::character varying)::text) <> ''::text)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tipo_tramite
    OWNER to demo;
-- Index: tipo_tramite_es_activo_index

-- DROP INDEX IF EXISTS public.tipo_tramite_es_activo_index;

CREATE INDEX IF NOT EXISTS tipo_tramite_es_activo_index
    ON public.tipo_tramite USING btree
    (es_activo ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: tipo_tramite_nombre_canon_index

-- DROP INDEX IF EXISTS public.tipo_tramite_nombre_canon_index;

CREATE UNIQUE INDEX IF NOT EXISTS tipo_tramite_nombre_canon_index
    ON public.tipo_tramite USING btree
    (lower(btrim(nombre::text)) COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

-- Trigger: trg_norm_tipo_tramite_codigo

-- DROP TRIGGER IF EXISTS trg_norm_tipo_tramite_codigo ON public.tipo_tramite;

CREATE OR REPLACE TRIGGER trg_norm_tipo_tramite_codigo
    BEFORE INSERT OR UPDATE OF codigo
    ON public.tipo_tramite
    FOR EACH ROW
    EXECUTE FUNCTION public.normalize_tipo_tramite_codigo();