-- Table: public.tipo_documento

-- DROP TABLE IF EXISTS public.tipo_documento;

CREATE TABLE IF NOT EXISTS public.tipo_documento
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    codigo character varying COLLATE pg_catalog."default" NOT NULL,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    es_activo boolean NOT NULL DEFAULT true,
    CONSTRAINT tipo_documento_primary_key PRIMARY KEY (id),
    CONSTRAINT tipo_documento_codigo_key UNIQUE (codigo),
    CONSTRAINT tipo_documento_nombre_not_blank_check CHECK (btrim(COALESCE(nombre, ''::character varying)::text) <> ''::text),
    CONSTRAINT tipo_documento_codigo_format_check CHECK (codigo::text ~ '^[a-z0-9_.]+$'::text)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tipo_documento
    OWNER to demo;
-- Index: tipo_documento_es_activo_index

-- DROP INDEX IF EXISTS public.tipo_documento_es_activo_index;

CREATE INDEX IF NOT EXISTS tipo_documento_es_activo_index
    ON public.tipo_documento USING btree
    (es_activo ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: tipo_documento_nombre_canon_unique_index

-- DROP INDEX IF EXISTS public.tipo_documento_nombre_canon_unique_index;

CREATE UNIQUE INDEX IF NOT EXISTS tipo_documento_nombre_canon_unique_index
    ON public.tipo_documento USING btree
    (lower(btrim(nombre::text)) COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

-- Trigger: normalize_codigo_insert

-- DROP TRIGGER IF EXISTS normalize_codigo_insert ON public.tipo_documento;

CREATE OR REPLACE TRIGGER normalize_codigo_insert
    BEFORE INSERT
    ON public.tipo_documento
    FOR EACH ROW
    EXECUTE FUNCTION public.normalize_tipo_documento_codigo();

-- Trigger: normalize_codigo_update

-- DROP TRIGGER IF EXISTS normalize_codigo_update ON public.tipo_documento;

CREATE OR REPLACE TRIGGER normalize_codigo_update
    BEFORE UPDATE OF codigo
    ON public.tipo_documento
    FOR EACH ROW
    EXECUTE FUNCTION public.normalize_tipo_documento_codigo();

-- Trigger: set_updated_at_update

-- DROP TRIGGER IF EXISTS set_updated_at_update ON public.tipo_documento;

CREATE OR REPLACE TRIGGER set_updated_at_update
    BEFORE UPDATE 
    ON public.tipo_documento
    FOR EACH ROW
    WHEN (old.* IS DISTINCT FROM new.*)
    EXECUTE FUNCTION public.set_updated_at();