-- Table: public.tramite

-- DROP TABLE IF EXISTS public.tramite;

CREATE TABLE IF NOT EXISTS public.tramite
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    radicado_por bigint NOT NULL,
    tipo_tramite_id bigint NOT NULL,
    comentario text COLLATE pg_catalog."default" NOT NULL,
    estado character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'RADICADO'::character varying,
    asignado_a bigint,
    numero_radicado bigint NOT NULL DEFAULT nextval('tramite_numero_radicado_seq'::regclass),
    finalizado_en timestamp with time zone,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT tramite_pkey PRIMARY KEY (id),
    CONSTRAINT tramite_numero_radicado_key UNIQUE (numero_radicado),
    CONSTRAINT tramite_asignado_a_fkey FOREIGN KEY (asignado_a)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT tramite_radicado_por_fkey FOREIGN KEY (radicado_por)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT tramite_tipo_tramite_id_fkey FOREIGN KEY (tipo_tramite_id)
        REFERENCES public.tipo_tramite (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT estado_nombre_chk CHECK (estado::text = ANY (ARRAY['RADICADO'::character varying, 'EN_PROCESO'::character varying, 'FINALIZADO'::character varying, 'RECHAZADO'::character varying]::text[])),
    CONSTRAINT tramite_comentario_not_blank_chk CHECK (btrim(COALESCE(comentario, ''::text)) <> ''::text)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tramite
    OWNER to demo;
-- Index: ix_tramite_asignado_estado

-- DROP INDEX IF EXISTS public.ix_tramite_asignado_estado;

CREATE INDEX IF NOT EXISTS ix_tramite_asignado_estado
    ON public.tramite USING btree
    (asignado_a ASC NULLS LAST, estado COLLATE pg_catalog."default" ASC NULLS LAST, actualizado_en DESC NULLS FIRST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: ix_tramite_func_activos

-- DROP INDEX IF EXISTS public.ix_tramite_func_activos;

CREATE INDEX IF NOT EXISTS ix_tramite_func_activos
    ON public.tramite USING btree
    (asignado_a ASC NULLS LAST, actualizado_en DESC NULLS FIRST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default
    WHERE estado::text = ANY (ARRAY['RADICADO'::character varying, 'EN_PROCESO'::character varying]::text[]);
-- Index: tramite_radicado_por_index

-- DROP INDEX IF EXISTS public.tramite_radicado_por_index;

CREATE INDEX IF NOT EXISTS tramite_radicado_por_index
    ON public.tramite USING btree
    (radicado_por ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: tramite_tipo_tramite_id_index

-- DROP INDEX IF EXISTS public.tramite_tipo_tramite_id_index;

CREATE INDEX IF NOT EXISTS tramite_tipo_tramite_id_index
    ON public.tramite USING btree
    (tipo_tramite_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

-- Trigger: set_actualizado_en_timestamp_update

-- DROP TRIGGER IF EXISTS set_actualizado_en_timestamp_update ON public.tramite;

CREATE OR REPLACE TRIGGER set_actualizado_en_timestamp_update
    BEFORE UPDATE 
    ON public.tramite
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();