-- Table: public.usuario

-- DROP TABLE IF EXISTS public.usuario;

CREATE TABLE IF NOT EXISTS public.usuario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email citext COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying COLLATE pg_catalog."default" NOT NULL,
    rol character varying COLLATE pg_catalog."default" NOT NULL,
    es_activo boolean NOT NULL DEFAULT true,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
    last_login_at timestamp with time zone,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT usuario_email_key UNIQUE (email),
    CONSTRAINT rol_nombre_chk CHECK (rol::text = ANY (ARRAY['ROLE_CIUDADANO'::character varying, 'ROLE_FUNCIONARIO'::character varying, 'ROLE_ADMINISTRATIVO'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.usuario
    OWNER to demo;
-- Index: ix_usuario_activo

-- DROP INDEX IF EXISTS public.ix_usuario_activo;

CREATE INDEX IF NOT EXISTS ix_usuario_activo
    ON public.usuario USING btree
    (es_activo ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: ix_usuario_rol_activo

-- DROP INDEX IF EXISTS public.ix_usuario_rol_activo;

CREATE INDEX IF NOT EXISTS ix_usuario_rol_activo
    ON public.usuario USING btree
    (rol COLLATE pg_catalog."default" ASC NULLS LAST, es_activo ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

-- Trigger: set_updated_at_usuario

-- DROP TRIGGER IF EXISTS set_updated_at_usuario ON public.usuario;

CREATE OR REPLACE TRIGGER set_updated_at_usuario
    BEFORE UPDATE 
    ON public.usuario
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();